### ISSUE TITLE
split team page into "Current Lab Members" and "Former Lab Members"

### ISSUE THREAD

**Issue by gregcaporaso** [caporaso-lab/caporaso-lab.github.io#19]
@ebolyen, could you put this on your to-do list? I'm thinking "Current Lab Members" would be on top, and "Former Lab Members" below.

**Comment by jairideout** [comment]
:+1:

**Comment by ebolyen** [comment]
Sure, that should be easy enough. I'll stick something on the calendar so I remember.

**Comment by gregcaporaso** [comment]
Thanks!
