### ISSUE TITLE
Remove "Now At" section from former team member profiles

### ISSUE THREAD

**Issue by ChrisKeefe** [caporaso-lab/caporaso-lab.github.io#74]
Is it time, or should this update wait until the Bokulich lab has a web site we can link?

**Comment by thermokarst** [comment]
FWIW, @nbokulich's profile is already listed in the "Former Members" section.

**Comment by thermokarst** [comment]
Also, I think we should drop the "Now At" sections from all of the team member profiles, this information become outdated pretty easily, and is probably better communicated via social media links, which are already present on most of the profiles.
